filebeat.inputs:  
  - type: log
    paths:
     - /var/log/gamelog/*/ActionLogs/*.log
    json.keys_under_root: true
    json.overwrite_keys: true
    tags: ["prod_logs"]
setup.template.name: ""
setup.template.pattern: ""
setup.template.enabled: false
setup.template.overwrite: true
processors: 
  - timestamp:
      field: time
      timezone:  America/New_York
      layouts:
        - '2006-01-02 15:04:05'
        - '2006-01-02 15:04:05.999'
      test:
        - '2019-06-22 16:33:51'
  - truncate_fields:
      fields:
        - time
      max_characters: 7
      fail_on_error: false
      ignore_missing: true
  - drop_fields:
      fields: ["host","agent","esc","input"]
output.elasticsearch: 
  hosts: ["10.11.144.63:9292"]
  indices:
    - index: "%{[logEvt]}-%{[time]}"
      when.contains:
        tags: "prod_logs"
